services:
  # 1. The Python Web Application Container
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    # Host port 8080 -> Container port 8080
    ports:
      - "8080:8080"  
    restart: always
    environment:
      # Database connection
      - MONGO_URI=mongodb://mongodb:27017/pogo  
      # Flask Settings for Development 
      - FLASK_ENV=Development
      - FLASK_DEBUG=True
      # Google Cloud Authentication
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
    volumes:
      # 1. Bind mount for application code (enables code changes and hot-reloading)
      # Equivalent to: --mount type=bind,source="./",target="/app"
      - .:/app
      
      # 2. Bind mount for the Google Application Credentials file (read-only)
      # Equivalent to: --mount type=bind,source="./application_default_credentials.json",target="...",readonly
      - ./application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    depends_on:
      - mongodb

  # 2. The MongoDB Database Container
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    # Volume mappings for data persistence and initial data import (.jsonl and .sh script)
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d 
    restart: always

# Define the volume to persist MongoDB data
volumes:
  mongo_data: